import type { Metadata } from "next";
import "./globals.css";
// import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import NavbarExample from "@/components/navbar-fix";

export const metadata: Metadata = {
  title: "PDAM Tirta Antokan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen flex-col">
          <NavbarExample />
          <main className="flex-1">
            <div className="relative">{children}</div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
